Added default Pantheon config for redis
teamdeeson/d7-quickstart pull request #15
Opened 2019-04-11 19:37 UTC by johnennewdeeson

Added default Redis config for D7 sites which was missing

2019-04-12 07:53 UTC, mikeddeeson reviewed
What if your site doesn't use redis or is not on Pantheon?

I think that if we are going to include this, then we should be checking for the environment var being pantheon at the very least

2019-04-12 07:59 UTC, angry-dan commented
Yeah I agree - I wouldn't want a site using Redis when running on Docker if it's not using Redis in prod.

2019-04-12 09:53 UTC, johnennewdeeson commented
So, some of these things are here for reference rather than 'YOU MUST HAVE IT IN YOUR PROJECT' - I'd just delete it if it didn't use Redis.

2019-04-12 11:58 UTC, adam-dg requested changes

2019-04-12 11:58 UTC, adam-dg commented on docroot/sites/all/conf/redis.settings.inc
> +if (SETTINGS_ENVIRONMENT !== 'local') {
We shouldn't be using the magic string "local" any more as we have predefined constants to use.

2019-04-12 11:58 UTC, adam-dg commented on docroot/sites/all/conf/redis.settings.inc
> +elseif (SETTINGS_INSTANCE === 'docker') {
We shouldn't be using the magic string "local" any more as we have predefined constants to use.

2019-05-04 13:15 UTC, johnennewdeeson commented on docroot/sites/all/conf/redis.settings.inc
> +elseif (SETTINGS_INSTANCE === 'docker') {
agreed

2019-05-04 13:15 UTC, johnennewdeeson commented on docroot/sites/all/conf/redis.settings.inc
> +if (SETTINGS_ENVIRONMENT !== 'local') {
agreed

2019-05-04 13:15 UTC, merged